# override standard exception controller
parameters:
    twig.controller.exception.class: AppBundle\Controller\ExceptionController

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
